### PR TITLE
Change teleport quality of service

### PR DESCRIPTION
**Pull request by goruha**
## What
* Made teleport quality of service `Guaranteed`

## Why
* To set the lowest priority GC for the pods

### CODE REVIEW

**Comment by Nuru** [comment]
I don't understand how this is supposed to help. You are reducing limits for the auth server (which needs higher limits because it is responsible for recording sessions as they happen) and increasing the requested CPU for the proxy server (which may not need it). Furthermore, these lower limits may trigger the [CPU throttling bug](https://github.com/kubernetes/kubernetes/issues/67577).

**Review by Nuru — COMMENTED** [review]
This seems like a bad idea to me. We should instead be setting critical pod annotations and working on pod priority classes. See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical and https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

**Comment by osterman** [comment]
@goruha I don't think you committed your latest changes? This PR does not seem to relate to the description

**Comment by goruha** [comment]
@Nuru @osterman this annotation is deprecated as of version 1.13 and will be removed in 1.1

**Comment by osterman** [comment]
@goruha please explain in the PR description how this works since it's something new for us.

**Comment by osterman** [comment]
image

**Comment by osterman** [comment]
image

**Review by osterman — APPROVED** [review]

**Comment by goruha** [comment]
helmfiles

**Pull request merged**
